export getCanonical from './getCanonical'
export getDefaultBreakPoints from './getDefaultBreakPoints'
export getDescription from './getDescription'
export getMetaImage from './getMetaImage'
export getTitle from './getTitle'
export getTwitterCard from './getTwitterCard'
