service: jared-lunde-pwa

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stack, 'development'}
  region: us-west-2

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "cloudformation:DescribeStackResource"
    Resource: "*"

functions:
  main:
    handler: render.main
    memorySize: 1536
    timeout: 12
    events:
      - http: GET /
      - http: 'GET {proxy+}'
    package:
      include:
        - package.json
        - dist/server/*
        - README.md
    environment:
      STACK: ${self:provider.stage}
      STAGE: ${self:custom.stack.stage}
      PLATFORM: server
    tags: ${self:custom.stack.main.tags}


plugins:
  - serverless-webpack
  - serverless-content-encoding
  - serverless-domain-manager
  - serverless-apigw-binary

custom:
  stack: ${file(./serverless.${self:provider.stage}.yml)}
  # Bundle creation
  webpack:
    webpackConfig: ${self:custom.stack.webpack.config}
    includeModules: true
    packager: 'yarn'
    packagerOptions:
      noFrozenLockFile: true
  customDomain:
    domainName: ${self:custom.stack.customDomain.domainName}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: ${self:custom.stack.customDomain.createRoute53Record}
  # Allows API Gateway to Gzip
  # Do not forget to set Binary Media Types in API Gateway -> Settings
  contentEncoding:
    minimumCompressionSize: 2048
  apigwBinary:
    types:
      - 'application/json'
      - 'text/html'
      - 'text/plain'
